image: $SKA_K8S_TOOLS_BUILD_DEPLOY_ALPINE

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint

include:
# Python packages lint
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/python-lint.gitlab-ci.yml'
